In [107]:
my_list=[1,2,3]

In [108]:
import numpy as np

In [109]:
arr=np.array(my_list)

In [110]:
arr

array([1, 2, 3])

In [111]:
my_mat=[[1,2,3],[4,5,6],[7,8,9]]

In [112]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [113]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [114]:
np.zeros(3)

array([0., 0., 0.])

In [115]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [116]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [117]:
np.ones(4)

array([1., 1., 1., 1.])

In [118]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [119]:
np.linspace(0,5,100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

In [120]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [121]:
np.random.rand(5)

array([0.16248143, 0.907354  , 0.60898271, 0.86347306, 0.21008188])

In [122]:
np.random.randn(2)

array([-0.97510338,  2.50355892])

In [123]:
np.random.randint(1,100,10)

array([ 3, 24,  1, 85, 71, 77, 13, 68, 72, 85], dtype=int32)

In [124]:
arr=np.arange(25)

In [125]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [126]:
ranarr=np.random.randint(0,50,10)

In [127]:
ranarr

array([40, 45,  0, 43, 31, 24,  0, 19, 24, 27], dtype=int32)

In [128]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [129]:
ranarr.max()

np.int32(45)

In [130]:
ranarr.min()

np.int32(0)

In [131]:
ranarr

array([40, 45,  0, 43, 31, 24,  0, 19, 24, 27], dtype=int32)

In [132]:
ranarr.argmax()

np.int64(1)

In [133]:
ranarr.argmin()

np.int64(2)

In [134]:
arr=arr.reshape(5,5)

In [135]:
arr.shape

(5, 5)

In [136]:
arr.dtype

dtype('int64')

In [137]:
# Numpy indexing selections

In [138]:
arr=np.arange(0,11)

In [139]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [140]:
arr[0]

np.int64(0)

In [141]:
arr[1:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [142]:
arr[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [143]:
arr[0:5]=100

In [144]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [145]:
arr=np.arange(0,11)

In [146]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [147]:
slice_of_arr=arr[0:6]

In [148]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [149]:
slice_of_arr[:]=99

In [150]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [151]:
arr_copy=arr.copy()

In [152]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [153]:
arr_copy[:]=100

In [154]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [155]:
arr_2d=np.array([[1,2,3],[12,32,23]])

In [156]:
arr_2d

array([[ 1,  2,  3],
       [12, 32, 23]])

In [157]:
arr_2d[0][0]

np.int64(1)

In [158]:
arr_2d[0]

array([1, 2, 3])

In [159]:
arr_2d[1][1]

np.int64(32)

In [160]:
arr_2d[1,1]

np.int64(32)

In [161]:
arr_2d[:1,1:]

array([[2, 3]])

In [162]:
arr=np.arange(1,11)

In [163]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [164]:
bool_arr=arr>5

In [165]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [166]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [167]:
arr[arr<3]

array([1, 2])

In [168]:
arr_2d=np.arange(50).reshape(5,10)

In [169]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

Numpy Operations
 - Array with Array
 - Array with Scalars
 - Universal Array Functions

In [170]:
arr=np.arange(0,11)

In [171]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [172]:
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [173]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [174]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [175]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [176]:
arr *100

array([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000])

In [177]:
arr/2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [178]:
arr / 0

C:\Users\Ashish Yadav\AppData\Local\Temp\ipykernel_21532\3942562399.py:1: RuntimeWarning: divide by zero encountered in divide
  arr / 0
C:\Users\Ashish Yadav\AppData\Local\Temp\ipykernel_21532\3942562399.py:1: RuntimeWarning: invalid value encountered in divide
  arr / 0


array([nan, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf])

In [179]:
arr/arr

C:\Users\Ashish Yadav\AppData\Local\Temp\ipykernel_21532\1862401812.py:1: RuntimeWarning: invalid value encountered in divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [180]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [181]:
1/arr

C:\Users\Ashish Yadav\AppData\Local\Temp\ipykernel_21532\255282349.py:1: RuntimeWarning: divide by zero encountered in divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [182]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [183]:
arr**2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [184]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [185]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [186]:
np.max(arr)

np.int64(10)

In [187]:
np.min(arr)

np.int64(0)

In [188]:
np. sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [189]:
np.log(arr)

C:\Users\Ashish Yadav\AppData\Local\Temp\ipykernel_21532\3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [190]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [191]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [192]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [193]:
np.arange(10,50+1,1)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [194]:
np.arange(10,50+1,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [195]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [196]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [197]:
np.random.rand()

0.42564067828520735

In [198]:
np.random.randn(25)

array([-0.55165086,  3.03446609,  0.39317244,  0.64297149,  1.4041025 ,
        1.53971486, -0.8160053 , -0.48931171,  0.32030696, -0.2995613 ,
        0.3713026 , -0.36922275,  1.2311379 , -0.36051013, -0.13163097,
       -0.95066677,  0.7636698 , -0.53392214,  0.34433884,  0.0851394 ,
        0.60641494,  1.13709366,  1.81455761, -1.46840349, -0.22352006])

In [199]:
np.arange(1,101).reshape(10,10)/100

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [201]:
np.linspace(0.01,1,100).reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [202]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])